-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- Source of truth: live Supabase project. Keep in sync after migrations.
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  location text,
  onboarding_code character NOT NULL UNIQUE CHECK (onboarding_code ~ '^[0-9]{6}$'::text),
  max_coaches integer,
  max_athletes integer,
  plan text NOT NULL DEFAULT 'trial'::text CHECK (plan = ANY (ARRAY['trial'::text, 'free'::text, 'pro'::text, 'enterprise'::text])),
  status text NOT NULL DEFAULT 'trial'::text CHECK (status = ANY (ARRAY['trial'::text, 'active'::text, 'suspended'::text])),
  trial_ends_at timestamp with time zone,
  billing_period_end timestamp with time zone,
  grace_period_end timestamp with time zone,
  max_devices integer,
  max_sessions_per_month integer,
  status_changed_at timestamp with time zone,
  is_grandfathered boolean NOT NULL DEFAULT false,
  CONSTRAINT programs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  role USER-DEFINED NOT NULL DEFAULT 'coach'::user_role,
  program_id uuid,
  first_name text,
  last_name text,
  email text,
  profile_pic text,
  position text,
  city text,
  state text,
  date_of_birth date,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  program_id uuid NOT NULL,
  created_by uuid,
  name text NOT NULL,
  team_type USER-DEFINED NOT NULL,
  parent_team_id uuid,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id),
  CONSTRAINT teams_parent_team_id_fkey FOREIGN KEY (parent_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.athletes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  program_id uuid NOT NULL,
  core_team_id uuid NOT NULL,
  coach_user_id uuid,
  created_by uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  city text,
  state text,
  height text,
  weight text,
  date_of_birth date,
  sport text,
  position text,
  CONSTRAINT athletes_pkey PRIMARY KEY (id),
  CONSTRAINT athletes_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT athletes_core_team_id_fkey FOREIGN KEY (core_team_id) REFERENCES public.teams(id),
  CONSTRAINT athletes_coach_user_id_fkey FOREIGN KEY (coach_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT athletes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  program_id uuid NOT NULL,
  team_id uuid NOT NULL,
  added_by uuid,
  coach_user_id uuid,
  athlete_id uuid,
  member_role text,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.profiles(user_id),
  CONSTRAINT team_members_coach_user_id_fkey FOREIGN KEY (coach_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT team_members_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id)
);
CREATE TABLE public.sessions (
  id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  program_id uuid,
  core_team_id uuid,
  athlete_id uuid,
  created_by uuid,
  version text,
  started_at_ms bigint,
  ended_at_ms bigint,
  grid_rows integer,
  grid_cols integer,
  device_model text,
  sampling_hz integer,
  calibration jsonb,
  raw jsonb NOT NULL,
  mode USER-DEFINED NOT NULL DEFAULT 'power'::session_mode,
  location jsonb,
  device_uid text,
  device_id text,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT sessions_core_team_id_fkey FOREIGN KEY (core_team_id) REFERENCES public.teams(id),
  CONSTRAINT sessions_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id),
  CONSTRAINT sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.events (
  event_id text NOT NULL,
  session_id text NOT NULL,
  t_start_ms bigint,
  t_end_ms bigint,
  duration_ms numeric,
  iei_prev_ms numeric,
  impulse_index numeric,
  rise_time_ms numeric,
  decay_time_ms numeric,
  angle_deg numeric,
  accuracy jsonb,
  strength_index jsonb,
  temporal jsonb,
  quality jsonb,
  raw jsonb NOT NULL,
  reaction_time_ms numeric,
  CONSTRAINT events_pkey PRIMARY KEY (event_id),
  CONSTRAINT events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.event_cells (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  event_id text NOT NULL,
  r integer NOT NULL,
  c integer NOT NULL,
  samples integer,
  v_min numeric,
  t_first_ms bigint,
  t_last_ms bigint,
  t_peak_ms bigint,
  v_peak numeric,
  CONSTRAINT event_cells_pkey PRIMARY KEY (id),
  CONSTRAINT event_cells_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(event_id)
);
CREATE TABLE public.session_summaries (
  session_id text NOT NULL,
  program_id uuid,
  core_team_id uuid,
  athlete_id uuid,
  num_events integer,
  session_duration_ms bigint,
  cadence_hz_avg numeric,
  cadence_hz_median numeric,
  iei_ms jsonb,
  longest_pause_ms bigint,
  peak_force_stats jsonb,
  impulse_stats jsonb,
  duration_ms_stats jsonb,
  angles_deg jsonb,
  most_contacted_cell_rc jsonb,
  center_of_mass_mm jsonb,
  heatmap jsonb,
  quality jsonb,
  date_of_record timestamp with time zone DEFAULT now(),
  mode USER-DEFINED,
  CONSTRAINT session_summaries_pkey PRIMARY KEY (session_id),
  CONSTRAINT session_summaries_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT session_summaries_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT session_summaries_core_team_id_fkey FOREIGN KEY (core_team_id) REFERENCES public.teams(id),
  CONSTRAINT session_summaries_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id)
);
CREATE TABLE public.devices (
  id text NOT NULL,
  program_id uuid,
  name text,
  fw_version text,
  fw_target text,
  features jsonb DEFAULT '{}'::jsonb,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  hw text,
  mode text,
  claimed_at timestamp with time zone,
  deactivated_at timestamp with time zone,
  CONSTRAINT devices_pkey PRIMARY KEY (id),
  CONSTRAINT devices_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
